CREATE TABLE `tbl_disbursement` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `burs_id` int(11) DEFAULT NULL,
  `office` int(11) DEFAULT NULL,
  `po_no` varchar(55) DEFAULT NULL,
  `dv` varchar(255) NOT NULL,
  `ors` varchar(255) NOT NULL,
  `sr` varchar(255) NOT NULL,
  `ppa` varchar(255) NOT NULL,
  `uacs` varchar(255) NOT NULL,
  `datereceived` date NOT NULL,
  `timereceived` time DEFAULT NULL,
  `payee` varchar(255) NOT NULL,
  `particular` varchar(255) NOT NULL,
  `amount` double NOT NULL,
  `tax` double NOT NULL,
  `gsis` double NOT NULL,
  `pagibig` double NOT NULL,
  `philhealth` double NOT NULL,
  `other` double NOT NULL,
  `total` double NOT NULL,
  `net` double NOT NULL,
  `date_proccess` date DEFAULT NULL,
  `datereleased` date NOT NULL,
  `timereleased` time NOT NULL,
  `datereturned` date DEFAULT NULL,
  `timereturned` time DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `flag` varchar(255) DEFAULT NULL,
  `orsdate` date DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL, -- Ensure this column exists for soft deletion
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
